---

- name: CQLSH configuration directory exists
  file:
    path: ~/.cassandra
    state: directory

- name: CQLSH configuration is installed
  template:
    src: cqlshrc
    dest: ~/.cassandra/cqlshrc
