---

- name: Packages key is installed
  apt_key:
    data: "{{ lookup('file', 'cassandra.key') }}"
    state: present

- name: Packages list is installed
  copy:
    src: cassandra.list
    dest: /etc/apt/sources.list.d/cassandra.list
    owner: root
    group: root
    mode: 0644
  register: cassandra_apt_sources

- name: Packages list is up to date (if sources were added)
  apt:
    update_cache: yes
  when: cassandra_apt_sources.changed

- name: Packages list is up to date (if cache expired)
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Temporary hack for Xenial
- include: xenial.yml

- name: Cassandra is installed
  apt:
    name: cassandra
    state: present
